#!/usr/bin/bash

function postescape {
	escaped=`echo "$1" | sed 's/ /%20/g; s/\*/\\*/g; s/\?/%3f/g; s/&/%38/g; s/+/%2b/g;'`
}

# usage: sparql $endpoint $query
function sparql {
	postescape "${2//:/http:\/\/odroid.0xFFFFFFFF.in\/psoc5lp\/ns\#}";
	curl -s -H content-type:application/x-www-form-urlencoded -H accept:text/plain -XPOST $1 -d "query=$escaped" | sed "s|http://odroid.0xFFFFFFFF.in/psoc5lp/ns#|:|g" | column -t
}

sparql "${1}" "${2}"
